### PR TITLE
GLOBAL is producing deprecation warnings in node V6

### PR DESCRIPTION
**Pull request by jmalins**
See here:
https://github.com/nodejs/node/wiki/Breaking-changes-between-v5-and-v6#globals

### CODE REVIEW

**Comment by nfarina** [comment]
Thanks for the PR! Will this break in previous Node versions? Or has the `global` lowercase var always been available?

**Comment by jmalins** [comment]
I just checked the docs for some older versions of node... the farthest back I went was 0.4.0, and it was there. Travis shows it passing on 0.10, FWIW. I can't vouch that 'global' has always been there, but it's seems like it's been there for a while.

**Comment by jmalins** [comment]
Actually, the node PR with the fix is informative... "This should be pretty low risk to remove", they say.
https://github.com/nodejs/node/pull/1838

**Comment by nfarina** [comment]
Awesome - I also should have paid attention to the CI checks right on this page where Travis tested it against old versions of Node already ;)

Thanks again for the PR.

**Comment by jmalins** [comment]
Not a problem. Thanks for producing this lib... it's exactly what we needed and has worked great for us.

**Comment by nfarina** [comment]
So very glad to hear it!

**Pull request merged**
